const KEY='fitness-checkin-yinhaoyu-v1',pad=n=>String(n).padStart(2,'0'),dateKey=(d=new Date())=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const plans=[
{type:'训练1：胸和三头',title:'胸＋三头',cardio:'跑步机：速度4.8–5.5km/h，坡度6–10%，20–30分钟；或爬楼机5–7档（约45–60步/分钟），15–20分钟',ex:[['挂片式上斜推胸',4,'8–10',['插片式上斜推胸','上斜史密斯卧推','上斜哑铃卧推']],['挂片式平板推胸',4,'8–10',['插片式平板推胸','宽角度推胸机','下斜推胸机','平板史密斯卧推','哑铃卧推']],['蝴蝶机夹胸',3,'12–15',['一体式夹胸飞鸟','低位绳索夹胸','宽角度推胸机（轻重量）']],['坐姿臂屈伸机',3,'10–12',['绳索下压','器械双杠臂屈伸','单臂绳索下压']],['绳索过顶臂屈伸',3,'10–12',['坐姿臂屈伸机','仰卧哑铃臂屈伸','单臂绳索过顶伸展']],['下斜推胸机（加练）',3,'10–12',['宽角度推胸机','平板推胸机（轻重量）','器械双杠臂屈伸']],['绳索夹胸（加练）',3,'12–15',['一体式夹胸飞鸟','哑铃飞鸟','蝴蝶机夹胸（轻重量）']],['绳索下压（加练）',3,'10–15',['坐姿臂屈伸机','器械双杠臂屈伸','单臂绳索下压']],['俯卧撑（加练）',2,'接近力竭前2次',['跪姿俯卧撑','宽角度推胸机（轻重量）','跳过这项']],['器械卷腹（可选）',3,'12–15',['垂直举腿','绳索卷腹','平板支撑','侧平板支撑','死虫式','Pallof抗旋转']]]},
{type:'训练2：背和二头',title:'背＋二头',cardio:'爬楼机：5–7档（约45–60步/分钟），15–20分钟；或跑步机速度4.8–5.6km/h、坡度6–10%，20–30分钟',ex:[['分动式高位下拉',4,'8–10',['双手一体式高位下拉','单臂高位下拉','高位下拉机','单臂绳索下拉']],['Flex胸托划船',4,'8–10',['分动式划船','器械坐姿划船','低位绳索划船']],['轨道式俯身划船',3,'10–12',['飞机拉背机','单臂器械划船','胸托T杠划船','单臂哑铃划船']],['反向蝴蝶机',3,'12–15',['一体式后束飞鸟','绳索面拉','俯身哑铃飞鸟']],['绳索弯举',3,'10–12',['哑铃弯举','牧师凳弯举机','坐姿弯举机']],['哑铃锤式弯举',3,'10–12',['绳索锤式弯举','弯举机中立握','交替哑铃弯举']],['直臂下压（加练）',3,'12–15',['单臂绳索下拉','器械直臂下拉','轻重量高位下拉']],['单臂器械划船（加练）',3,'10–12',['分动式划船','单臂哑铃划船','低位绳索划船']],['绳索面拉（加练）',3,'12–15',['反向蝴蝶机','一体式后束飞鸟','俯身哑铃飞鸟']],['牧师凳弯举机（加练）',3,'10–12',['坐姿弯举机','绳索弯举','交替哑铃弯举']],['器械卷腹（可选）',3,'12–15',['垂直举腿','绳索卷腹','平板支撑','侧平板支撑','死虫式','Pallof抗旋转']]]},
{type:'训练3：腿和肩',title:'腿＋肩',cardio:'跑步机：速度4–4.8km/h，坡度0–3%，15–20分钟；腿部疲劳或膝盖不舒服时改平路3.8–4.5km/h、10–15分钟，必要时跳过',ex:[['哈克深蹲机',4,'8–10',['45度倒蹬机','斜蹲机','史密斯深蹲']],['坐姿腿弯举机',3,'10–12',['俯卧腿弯举机','站姿单腿弯举机','哑铃罗马尼亚硬拉']],['腿屈伸机',3,'10–15',['单腿腿屈伸','45度倒蹬机（轻重量）','哈克深蹲机（轻重量）']],['器械臀推机',3,'8–12',['史密斯臀推','杠铃臀推','臀外展机']],['挂片式推肩机',4,'8–10',['插片式推肩机','坐姿肩推机','史密斯肩推','坐姿哑铃肩推']],['坐姿侧平举机',3,'12–15',['挂片式飞肩机','单臂绳索侧平举','哑铃侧平举']],['反向蝴蝶机',3,'12–15',['一体式后束飞鸟','绳索面拉','俯身哑铃飞鸟']],['45度倒蹬机（加练）',3,'10–15',['哈克深蹲机（轻重量）','斜蹲机','史密斯深蹲']],['臀外展机（加练）',3,'12–20',['站姿髋外展机','臀推机（轻重量）','徒手侧向走']],['臀内收机（加练）',3,'12–20',['站姿髋内收','宽站距倒蹬（轻重量）','相扑深蹲']],['腿举机提踵（加练）',3,'12–20',['史密斯提踵','徒手提踵','台阶提踵']],['绳索面拉（加练）',3,'12–15',['反向蝴蝶机','一体式后束飞鸟','俯身哑铃飞鸟']],['器械卷腹（可选）',3,'12–15',['垂直举腿','绳索卷腹','平板支撑','侧平板支撑','死虫式','Pallof抗旋转']]]},
{type:'恢复训练',title:'恢复训练 / 无痛替换',cardio:'只做轻松有氧：跑步机速度3.8–4.8km/h、坡度0–2%，10–20分钟；任何不适加重就停止',ex:[['腿屈伸机（轻重量）',3,'12–15',['坐姿腿弯举机（轻重量）','臀外展机','徒手深蹲']],['臀外展机',3,'12–15',['臀内收机','站姿髋外展机','徒手臀桥']],['腿举机提踵',3,'12–15',['史密斯提踵','徒手提踵','台阶提踵']],['死虫式',3,'每侧10',['鸟狗式','平板支撑','Pallof抗旋转']],['轻松有氧',1,'10–20分钟',['跑步机低坡走','跑步机平路慢走','不舒服时跳过有氧']]]},
{type:'自由训练',title:'完全自由训练',cardio:'有余力再做跑步机低坡走或爬楼机10–20分钟；今天身体状态优先，不强制完成有氧',ex:[['自定义动作1',3,'自定',['挂片式上斜推胸','分动式高位下拉','哈克深蹲机']],['自定义动作2',3,'自定',['Flex胸托划船','坐姿腿弯举机','坐姿臂屈伸机']],['自定义动作3',3,'自定',['蝴蝶机夹胸','绳索下压','挂片式推肩机']],['自定义动作4',3,'自定',['坐姿侧平举机','器械臀推机','反向蝴蝶机']],['自定义动作5（可跳过）',3,'自定',['绳索弯举','腿屈伸机','器械卷腹']]]}
];
const warmups=[
{title:'胸＋三头专项热身｜约10–12分钟',steps:[['跑步机全身升温','5分钟','速度4.0–5.0km/h、坡度0–2%；身体微微发热即可，不需要跑。'],['肩胛与胸椎动态活动','每项8–10次','肩绕环、肩胛前伸后收、站姿胸椎旋转；动作慢，不做长时间静态拉伸。'],['肩袖与推举激活','1–2轮','龙门架单臂外旋每侧12次＋靠墙滑手10次；只用很轻重量，肩前侧必须无痛。'],['第一项推胸递增热身','2–3组','空载或很轻重量×15；约正式重量50%×8–10；需要时约70%×3–5。全部保留余力。'],['第二项推胸试轨迹','1组×10次','用轻重量先试当天机器的座椅高度和轨迹，肩或胸不舒服就直接换备选动作。']]},
{title:'背＋二头专项热身｜约10–12分钟',steps:[['跑步机全身升温','5分钟','速度4.0–5.0km/h、坡度0–2%；手臂自然摆动，让背部和肩部逐渐热起来。'],['肩胛与胸椎动态活动','每项8–10次','肩绕环、猫牛式或站姿胸椎旋转、肩胛下沉练习；不要猛甩手臂。'],['背部激活','1–2轮','直臂下压12次＋轻重量绳索面拉12次；先感受肩胛下沉和后收。'],['高位下拉递增热身','2–3组','很轻重量×15；约正式重量50%×8–10；需要时约70%×3–5，不做到力竭。'],['第一项划船试轨迹','1组×10次','轻重量完成，找到胸贴垫、肘向后拉的轨迹，再开始正式组。']]},
{title:'腿＋肩专项热身｜约12–15分钟',steps:[['跑步机全身升温','6–8分钟','速度3.8–4.8km/h、坡度0–2%；膝盖不舒服就减速并保持平路。'],['踝、膝、髋动态活动','每侧8–10次','扶墙踝关节前移、髋绕环、前后摆腿；全程在无痛范围内。'],['下肢激活','2轮','徒手深蹲10次＋徒手臀桥12次；膝盖跟脚尖同向，顶部收紧臀部。'],['哈克或倒蹬递增热身','3组','空载或很轻重量×12–15；约正式重量50%×8；约70%×3–5。逐级加重，不跨大档。'],['肩部训练前再激活','1–2轮','开始练肩前做肩绕环10次、龙门架外旋每侧12次，再用轻重量推肩10次。']]},
{title:'恢复训练热身｜约8–10分钟',steps:[['低强度升温','5–8分钟','跑步机速度3.5–4.5km/h、坡度0%；呼吸轻松，任何不适加重就停止。'],['全身疼痛自检','约1分钟','分别活动肩、肘、腕、髋、膝、踝；记录今天不能无痛完成的方向。'],['无痛动态活动','每项8次','只选舒服的关节活动，不压痛点、不弹震、不强行拉伸。'],['第一个动作试做','1–2组','使用非常轻的重量做12–15次；症状没有增加再继续恢复训练。']]},
{title:'自由训练通用热身｜约10分钟',steps:[['跑步机全身升温','5分钟','速度4.0–5.0km/h、坡度0–2%；达到微微发热即可。'],['全身动态活动','每项8–10次','肩绕环、胸椎旋转、髋绕环、摆腿和徒手深蹲，按今天要练的部位取舍。'],['目标部位激活','1–2轮','上肢选外旋、面拉或直臂下压；下肢选徒手深蹲和臀桥。全部轻松完成。'],['第一个复合动作递增热身','2–3组','很轻重量×12–15；约正式重量50%×8；需要时约70%×3–5，再进入正式组。']]}
];
const cooldowns=['有氧结束后慢走3–5分钟，让呼吸恢复；门框胸肌拉伸和三头拉伸各20–30秒×1–2，只保持轻微牵拉感。','有氧结束后慢走3–5分钟；扶固定架做背阔肌后坐拉伸，二头肌轻拉伸，每侧20–30秒×1–2。','有氧结束后平路慢走3–5分钟；股四头、臀、腿后侧、小腿和肩部各轻拉20–30秒，不压疼痛点。','结束前轻松走3–5分钟并做无痛范围内的放松呼吸；不强行拉伸任何不舒服的部位。','结束前慢走3–5分钟；只拉伸当天训练部位，每个姿势20–30秒×1–2，不弹震。'];
let warmupState={};
const mainPlans=plans.slice(0,3);let selectedPlan=0;
const volumeLimits={quick:[4,5,6,4,4],standard:[7,8,9,5,5],enhanced:[10,11,13,7,7]},volumeLabels={quick:'快速',standard:'标准',enhanced:'加强'};
plans.forEach(p=>p.library=[...p.ex]);let sessionVolume='standard';
function volumeLimit(){return volumeLimits[sessionVolume]?.[selectedPlan]??plans[selectedPlan].library.length}
function ensureVolumeSelector(){const host=document.querySelector('.session-choices');if(!host||$('sessionVolumeChoice'))return;const label=document.createElement('label');label.className='plan-choice volume-choice';label.innerHTML='<span>本次训练量</span><select id="sessionVolumeChoice"><option value="quick">快速｜4–6个动作</option><option value="standard">标准｜7–9个动作</option><option value="enhanced">加强｜10–13个动作</option></select>';host.append(label);$('sessionVolumeChoice').value=sessionVolume;$('sessionVolumeChoice').onchange=e=>{sessionVolume=e.target.value;renderTracker()}}
ensureVolumeSelector();
const legacyPlanTypes={'训练1：胸和二头':0,'训练2：背和三头':1,'训练3：腿和肩':2};
const planIndexForType=type=>{const current=mainPlans.findIndex(p=>p.type===type);return current>=0?current:(legacyPlanTypes[type]??-1)};
const exerciseGuides={
'坐姿胸推机':['调座椅让把手对准胸中部，肩胛后收并贴靠背垫，双脚踩稳。','向前推时呼气，肘不要锁死；用2–3秒缓慢还原。','不要耸肩、含胸或用腰把重量顶出去。'],
'上斜哑铃卧推':['凳背约30°，哑铃从上胸两侧开始，肩胛向后向下收紧。','向上推时呼气，哑铃保持稳定；下降到无痛且可控的位置。','不要把凳背调得太陡、不要碰撞哑铃或过度下放。'],
'蝴蝶机夹胸':['座椅调到手肘略低于肩，胸贴近靠垫，手肘保持微弯。','胸肌发力把手臂合到胸前，停顿1秒，再慢慢打开。','不要弓背、耸肩，也不要让配重片猛烈碰撞。'],
'绳索下压':['滑轮调到高位，上臂贴近身体，身体可轻微前倾。','只伸手肘，底部停顿并呼气，回程到前臂略高于水平。','不要用肩膀压、甩身体或让手肘前后跑。'],
'绳索过顶臂屈伸':['背对龙门架站稳，上臂靠近头部，肘朝前。','伸直手肘时呼气，回程缓慢，保持上臂基本不动。','不要塌腰、耸肩或用过大的重量拉扯肘关节。'],
'器械双杠臂屈伸':['调好座椅和辅助重量，肩膀向下，手腕保持中立。','向下压到手肘接近伸直，缓慢回到无痛位置。','肩前侧不舒服就停止，改绳索下压或坐姿臂屈伸机。'],
'高位下拉机':['压腿垫固定大腿，握距略宽于肩，胸口微抬。','先下沉肩胛，再把手柄拉向锁骨上方，回程完全控制。','不要大幅后仰、拉到颈后或借身体摆动。'],
'坐姿划船机':['双脚踩稳，胸托式器械让胸贴垫；无胸托时保持脊柱中立。','先把肩胛向后收，再让手肘沿身体两侧拉向肋骨。','不要含胸、耸肩或用腰部前后甩动。'],
'单臂哑铃划船':['一手一膝支撑长凳，背部平稳，工作侧肩膀自然下沉。','把手肘拉向髋部，顶端停顿，缓慢把哑铃放下。','不要旋转躯干、耸肩或把哑铃拉向胸口。'],
'反向蝴蝶机':['面对靠垫坐好，胸贴垫，把手与肩大致同高。','后束带动手臂向两侧打开，肩胛轻收，再缓慢回程。','不要耸肩、过度夹背或用惯性弹动。'],
'哑铃弯举':['站稳并收紧腹部，上臂贴近身体，手腕保持中立。','弯曲手肘时呼气，顶端不抬肩，2–3秒缓慢下放。','不要后仰甩动、手肘前冲或折手腕。'],
'哑铃锤式弯举':['掌心始终相对，上臂夹紧身体，肩膀放松。','弯举到前臂接近竖直，停顿后缓慢下放。','不要借腰甩动或让手肘大幅向前。'],
'45度腿举机':['腰背贴垫，双脚与肩同宽放在踏板中部，脚尖与膝盖同向。','下放到腰不卷起的位置，再用全脚掌推回，顶部不锁膝。','不要膝内扣、脚跟抬起或为了更深让臀部离垫。'],
'坐姿腿弯举机':['膝关节对准机器转轴，压腿垫固定大腿，滚垫在脚踝后上方。','脚跟向下后方卷，停顿后缓慢伸回。','不要臀部离座、借力弹动或过度勾脚尖。'],
'保加利亚分腿蹲':['后脚放在凳上，前脚站到下蹲时小腿接近竖直的位置。','身体略前倾，前脚全脚掌发力起身；需要时扶固定物。','不要追求不稳的大重量，膝或髋不适就改腿屈伸机。'],
'坐姿肩推机':['把手起始略低于肩，背部贴垫，肋骨不要外翻。','向上推时呼气，顶部不锁肘，下降到无痛位置。','不要耸肩、塌腰或把手柄放得过低。'],
'哑铃侧平举':['选小重量，手肘微弯并略高于手腕，肩膀下沉。','手肘带动哑铃抬到肩高附近，再缓慢放下。','不要耸肩、甩动身体或把手腕抬得高于手肘。'],
'上斜推胸':['座椅调到把手对准上胸，肩胛向后向下贴紧靠垫，双脚踩稳。','沿器械轨迹向前上方推，顶部不锁肘，用2–3秒控制回程。','不要耸肩、塌腰或把手柄放得过低；肩前侧不适立即换动作。'],
'平板推胸':['让把手对准胸中部，肩胛后收贴垫，手腕保持中立。','胸部发力推至手肘接近伸直，停顿后缓慢回到无痛位置。','不要含胸、弹震配重或为了加重量缩短动作。'],
'坐姿臂屈伸机':['调座椅让手柄位于身体两侧，上臂稳定，肩膀主动下沉。','只伸直手肘并在底部短暂停顿，再缓慢回程。','不要耸肩、用身体下压；肘或肩出现刺痛就停止。'],
'分动式高位下拉':['用压腿垫固定大腿，左右手柄分别握稳，胸口微抬。','先下沉肩胛，再让手肘向下靠近肋骨；可双臂同步或单臂完成。','不要大幅后仰、耸肩或用身体摆动带下重量。'],
'胸托划船':['调好座椅让胸骨贴住胸垫，双脚踩稳，手臂自然伸直。','先收肩胛再向后拉手肘，顶端停顿，回程时保持胸贴垫。','不要抬胸离垫、耸肩或用腰部甩动。'],
'轨道式俯身划船':['胸腹贴稳支撑垫，握住手柄，颈部与脊柱保持自然。','手肘沿轨道向后拉至身体两侧，停顿后控制下放。','不要抬头过度、弓背或借腿和腰弹动。'],
'哈克深蹲机':['肩背贴垫，双脚放在踏板中上部并与肩同宽，膝盖朝脚尖方向。','解除保险后控制下蹲到腰背不卷起，再用全脚掌推回。','不要膝内扣、脚跟离板或在顶部锁死膝盖。'],
'器械臀推机':['肩胛下缘靠稳背垫，双脚踩实，髋部固定好护垫或绑带。','收紧腹部并夹臀把髋推起，顶部躯干接近水平，再控制下放。','不要用腰过度后仰、脚位太远或快速弹起重量。'],
'腿屈伸机':['膝关节对准机器转轴，滚垫放在脚踝前方，腰背贴垫。','伸膝抬起滚垫，顶端停顿但不锁死，再缓慢下降。','不要踢甩重量、臀部离座或让膝盖出现疼痛。'],
'器械侧平举':['调座椅让机器转轴接近肩关节，手肘贴住臂垫，肩膀下沉。','用手肘带动臂垫抬到肩高附近，停顿后控制下降。','不要耸肩、弹震配重或抬得明显高于肩。'],
'器械卷腹':['坐稳并固定双脚，手握把手或让肩部贴住力臂，先轻收下巴。','肋骨向骨盆靠近完成卷腹，底部呼气，缓慢回到起始位。','不要只用手臂下拉、猛低头或用髋部前后摆动。'],
'垂直举腿':['前臂压稳支撑垫，背部贴靠垫，肩膀远离耳朵。','收紧腹部，把膝盖卷向胸口，停顿后慢慢放下。','不要甩腿、塌腰或只靠髋屈肌快速摆动。'],
'绳索夹胸':['龙门架滑轮调到合适高度，前后站稳，手肘保持微弯。','胸肌发力让双手向身前合拢，停顿后缓慢打开到无痛位置。','不要耸肩、手臂完全伸直或用身体冲击重量。'],
'直臂下压':['面对高位滑轮站稳，髋部微屈，手臂近乎伸直。','肩胛下沉并把把手压向大腿，停顿后控制回到头顶前方。','不要弯肘变成三头下压，也不要塌腰甩动。'],
'绳索面拉':['滑轮调到面部高度，使用绳索，双脚前后站稳。','手肘向外打开，把绳索两端拉向耳朵两侧，肩后束发力。','不要耸肩、仰腰或选择无法控制的重量。'],
'牧师凳弯举机':['上臂完整贴住斜垫，手腕保持中立，座椅调到肩膀放松。','弯举时不抬上臂，顶端停顿，慢慢伸肘但不要锁死。','不要让上臂离垫、弹震配重或过度伸直肘关节。'],
'臀外展机':['背部贴垫坐稳，双腿外侧贴住挡垫，腹部轻收。','臀部发力把膝盖向外打开，停顿后缓慢合回。','不要用身体后仰借力或让配重片猛烈碰撞。'],
'臀内收机':['坐稳并让大腿内侧贴住挡垫，先选择舒适的打开幅度。','大腿内侧发力把双腿合拢，停顿后控制打开。','不要强行追求过大幅度、弹震或夹腿过快。'],
'腿举机提踵':['在倒蹬机上只把前脚掌踩住踏板下缘，膝盖保持微弯。','脚跟缓慢下降后用前脚掌推起，顶端充分收紧小腿。','不要弹震、锁膝或让脚掌滑出踏板。'],
'俯卧撑':['双手略宽于肩，头、背、髋保持一条直线，腹部收紧。','胸口向地面下降到可控位置，再推回并保持肩胛稳定。','不要塌腰、耸肩或为了次数牺牲身体姿势。']
};
exerciseGuides['推肩机']=exerciseGuides['坐姿肩推机'];exerciseGuides['侧平举机']=exerciseGuides['器械侧平举'];
const genericGuide=['先调好器械并用轻重量试做，关节对准器械转轴，身体保持稳定。','发力时呼气、还原时吸气；全程慢而可控，只在无痛范围内训练。','不要借力甩动、憋气或为了完成次数牺牲动作。'];
const directVideos={'坐姿胸推机':'https://www.bilibili.com/video/BV1cUevzTEb4/','高位下拉机':'https://www.bilibili.com/video/BV1gU4y1v71z/','坐姿划船机':'https://www.bilibili.com/video/BV1xE411x7xV/'};
function normalizedName(name){return name.replace(/[（(].*?[）)]/g,'').replace(/轻重量|自定义动作\d*/g,'').trim()}
function guideFor(name){const clean=normalizedName(name);if(exerciseGuides[clean])return exerciseGuides[clean];const hit=Object.keys(exerciseGuides).find(k=>clean.includes(k)||k.includes(clean));return hit?exerciseGuides[hit]:genericGuide}
function videoFor(name){const clean=normalizedName(name);return directVideos[clean]||`https://search.bilibili.com/all?keyword=${encodeURIComponent(clean+' 动作教学 健身')}`}
function guideHtml(name){const [setup,move,avoid]=guideFor(name);return `<details class="technique"><summary>看动作要领和 B 站教学</summary><div><p><b>准备：</b>${esc(setup)}</p><p><b>怎么做：</b>${esc(move)}</p><p><b>避免：</b>${esc(avoid)}</p><a class="video-link" href="${videoFor(name)}" target="_blank" rel="noopener">▶ 打开 B 站教学视频</a></div></details>`}
const GYMS=['铁锤健身·常青藤','唤燃星24小时·许坦东街店'];
const equipmentCatalog=[['chestPress','多角度推胸（宽角度 / 上斜 / 平板 / 下斜）'],['pecDeck','蝴蝶机 / 反向蝴蝶 / 一体式飞鸟'],['pulldown','高位下拉（分动 / 单臂 / 双手）'],['row','划船机（Flex / 分动 / 轨道式）'],['cable','龙门架 / 绳索'],['legPress','45°倒蹬 / 哈克深蹲'],['hipThrust','臀推机'],['legCurl','腿弯举（坐姿 / 俯卧）'],['legExtension','腿屈伸机'],['shoulderPress','推肩机（挂片 / 插片）'],['lateralRaise','侧平举 / 飞肩机'],['dipStation','双杠 / 垂直举腿架'],['armMachine','弯举 / 坐姿臂屈伸机'],['hipMachine','臀外展 / 内收 / 站姿髋外展'],['abCrunch','卷腹机'],['smith','史密斯机'],['dumbbell','哑铃'],['barbell','杠铃 / 深蹲架'],['bench','训练长凳'],['treadmill','跑步机'],['stairClimber','爬楼机']];
function requirementsFor(name){const n=normalizedName(name);const r=[];if(/上斜哑铃卧推|哑铃卧推|哑铃飞鸟|仰卧哑铃|单臂哑铃划船/.test(n))r.push('dumbbell','bench');else if(/哑铃/.test(n))r.push('dumbbell');if(/台阶/.test(n))r.push('bench');if(/史密斯/.test(n))r.push('smith');if(/杠铃/.test(n))r.push('barbell');if(/绳索|龙门架|Pallof/.test(n))r.push('cable');if(/蝴蝶|后束飞鸟|一体式夹胸|一体式后束/.test(n))r.push('pecDeck');if(/胸推|推胸|器械卧推|器械推胸/.test(n))r.push('chestPress');if(/高位下拉|器械下拉/.test(n))r.push('pulldown');if(/划船|T杠|飞机拉背/.test(n))r.push('row');if(/腿举|倒蹬|哈克|斜蹲/.test(n))r.push('legPress');if(/臀推机/.test(n))r.push('hipThrust');if(/腿弯举/.test(n))r.push('legCurl');if(/腿屈伸/.test(n))r.push('legExtension');if(/推肩机|肩推机|器械推举机/.test(n))r.push('shoulderPress');if(/器械侧平举|坐姿侧平举|侧平举机|飞肩机/.test(n))r.push('lateralRaise');if(/垂直举腿|悬垂举腿|器械双杠/.test(n))r.push('dipStation');if(/牧师凳弯举机|坐姿弯举机|弯举机中立握|坐姿臂屈伸机/.test(n))r.push('armMachine');if(/臀外展机|臀内收机|站姿髋外展机/.test(n))r.push('hipMachine');if(/器械卷腹|卷腹机/.test(n))r.push('abCrunch');if(/跑步机/.test(n))r.push('treadmill');if(/爬楼机/.test(n))r.push('stairClimber');return [...new Set(r)]}
let data;try{data=JSON.parse(localStorage.getItem(KEY))||{}}catch{data={}}
function ensureData(){data.checkins??=[];data.records??=[];data.body??=[];data.wearable??=[];data.redeemed??=[];data.hammerUsed??=data.records.filter(r=>r.gym?.includes('铁锤')&&planIndexForType(r.type)>=0).length;data.gymEquipment??={};GYMS.forEach(g=>{data.gymEquipment[g]??={};equipmentCatalog.forEach(([id])=>data.gymEquipment[g][id]??=true)});if((data.equipmentProfileVersion||0)<2){const huanran=data.gymEquipment[GYMS[1]];equipmentCatalog.forEach(([id])=>huanran[id]=true);huanran.elliptical=false;huanran.bike=false;huanran.calfMachine=false;data.equipmentProfileVersion=2}}
ensureData();const save=()=>localStorage.setItem(KEY,JSON.stringify(data));save();
const autoGym=()=>GYMS[1];let sessionGym=autoGym();
function isExerciseAvailable(name,gym=sessionGym){return requirementsFor(name).every(id=>data.gymEquipment[gym]?.[id]!==false)}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tab-page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
function nextIndex(){const main=[...data.records].reverse().find(r=>planIndexForType(r.type)>=0);return main?(planIndexForType(main.type)+1)%3:0}
function lastExercise(name){for(const r of [...data.records].reverse()){const x=r.sets?.find(e=>e.name===name);if(x)return x}return null}
function doneEntries(exercise){return(exercise?.entries||[]).filter(x=>x.done).map(x=>({kg:+x.kg||0,reps:+x.reps||0}))}
function historyHint(name,n,reps){const last=lastExercise(name),done=doneEntries(last);return last?`上次：${done.map(x=>`${x.kg}kg×${x.reps}`).join(' / ')||'已记录'}`:`目标：${n}组 × ${reps}次`}
function progressionTip(name,n,reps){const last=lastExercise(name),done=doneEntries(last);if(!last)return '首次记录：先选能规范完成、还保留约2次余力的重量';if(!done.length||!done.some(x=>x.kg))return '下次请补录重量，系统才能给出加重建议';const weight=Math.max(...done.map(x=>x.kg)),targets=String(reps).match(/\d+/g)?.map(Number)||[],high=targets.at(-1)||0,allDone=done.length>=n,allHit=high&&done.every(x=>x.reps>=high);if(allDone&&allHit){const lower=/腿举|深蹲|分腿蹲|腿弯|腿屈|硬拉|臀|提踵/.test(name),next=weight+(lower?2.5:1);return `全部达标：下次建议 ${next}kg（或增加器械最小一档）`}if(!allDone)return `还有正式组未完成：下次先保持 ${weight}kg，把组数做满`;return `次数尚未全部达标：下次保持 ${weight}kg，先把动作做稳`}
selectedPlan=nextIndex();
function renderWarmup(){const w=warmups[selectedPlan]||warmups[4],state=warmupState[selectedPlan]??=Array(w.steps.length).fill(false);if(state.length!==w.steps.length)warmupState[selectedPlan]=Array(w.steps.length).fill(false);$('warmupTitle').textContent=w.title;$('warmupTracker').innerHTML=w.steps.map(([name,amount,detail],i)=>`<label class="warmup-step ${warmupState[selectedPlan][i]?'checked':''}" data-name="${esc(name)}"><input class="warmup-check" type="checkbox" data-index="${i}" ${warmupState[selectedPlan][i]?'checked':''}><span><b>${i+1}. ${esc(name)}</b><small>${esc(amount)}</small><em>${esc(detail)}</em></span></label>`).join('');const update=()=>{const boxes=[...document.querySelectorAll('.warmup-check')];boxes.forEach(x=>{warmupState[selectedPlan][+x.dataset.index]=x.checked;x.closest('.warmup-step').classList.toggle('checked',x.checked)});$('warmupProgress').textContent=`${boxes.filter(x=>x.checked).length}/${boxes.length}`};document.querySelectorAll('.warmup-check').forEach(x=>x.onchange=update);update()}
function renderTracker(){
const p=plans[selectedPlan],recommended=mainPlans[nextIndex()],total=data.records.length;p.ex=p.library.slice(0,volumeLimit());$('planChoice').value=String(selectedPlan);$('sessionGymChoice').value=sessionGym;$('nextTitle').textContent=p.title;$('nextMeta').textContent=`系统推荐：${recommended.title}｜当前选择：${p.title}｜训练量：${volumeLabels[sessionVolume]}（${p.ex.length}个动作）｜地点：${sessionGym}`;$('hammerLeft').textContent=total;$('postCardio').innerHTML=`<b>本次选择对应的练后有氧</b><br>${p.cardio}<div class="cooldown-note"><b>最后：降速整理与轻拉伸｜5–8分钟</b><br>${cooldowns[selectedPlan]}</div>`;renderWarmup();
$('setTracker').innerHTML=p.ex.map(([base,n,reps,alts],ei)=>{const available=[base,...alts].filter(x=>isExerciseAvailable(x)),name=available[0]||base,options=available.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join(''),unavailable=available.length?'':`<span class="exercise-unavailable">这家店没有匹配器械：请选择自定义动作、重新勾选器械或跳过</span>`;return `<div class="exercise-track" data-name="${esc(name)}" data-groups="${n}" data-reps="${esc(reps)}"><h3>${ei+1}. <span class="exercise-name">${esc(name)}</span></h3><span class="last-time">${esc(historyHint(name,n,reps))}</span><span class="progression-tip">${esc(progressionTip(name,n,reps))}</span>${unavailable}<div class="exercise-actions"><label>按本店器械选择动作<select class="alt-select">${options}<option value="__custom">自定义其他动作…</option></select></label><label class="skip-label"><input class="skip-exercise" type="checkbox">跳过这个动作</label></div><p class="alternative-note">这里只显示该门店已勾选器械对应的动作；轻重量试做，无痛再继续。</p><div class="exercise-guide">${guideHtml(name)}</div><div class="sets">${Array.from({length:n},(_,i)=>`<div class="set-box"><label><input class="set-check" type="checkbox">第${i+1}组</label><input class="kg" type="number" step="0.5" min="0" placeholder="重量kg"><input class="reps" type="number" min="0" placeholder="次数"></div>`).join('')}</div></div>`}).join('');
document.querySelectorAll('.alt-select').forEach(x=>x.onchange=()=>{const card=x.closest('.exercise-track');let name=x.value;if(name==='__custom'){name=prompt('输入你现场实际使用的动作名称：')?.trim()||card.dataset.name}card.dataset.name=name;card.querySelector('.exercise-name').textContent=name;card.querySelector('.last-time').textContent=historyHint(name,+card.dataset.groups,card.dataset.reps);card.querySelector('.progression-tip').textContent=progressionTip(name,+card.dataset.groups,card.dataset.reps);card.querySelector('.exercise-guide').innerHTML=guideHtml(name)});
document.querySelectorAll('.skip-exercise').forEach(x=>x.onchange=()=>x.closest('.exercise-track').classList.toggle('skipped',x.checked));document.querySelectorAll('.set-check').forEach(x=>x.onchange=()=>{if(x.checked){const card=x.closest('.exercise-track');startRest(restSeconds(card.dataset.name),card.dataset.name)}})}
function renderEquipmentProfile(){const gym=$('equipmentGym').value||GYMS[0];$('equipmentChecks').innerHTML=equipmentCatalog.map(([id,label])=>`<label class="equipment-check"><input type="checkbox" data-equipment="${id}" ${data.gymEquipment[gym][id]?'checked':''}>${esc(label)}</label>`).join('');document.querySelectorAll('[data-equipment]').forEach(x=>x.onchange=()=>{if(document.querySelector('.set-check:checked')){if(!confirm('修改器械档案会重新生成当前动作，确定继续吗？')){x.checked=!x.checked;return}}data.gymEquipment[gym][x.dataset.equipment]=x.checked;save();if(gym===sessionGym)renderTracker()})}
function setAllEquipment(value){const gym=$('equipmentGym').value;equipmentCatalog.forEach(([id])=>data.gymEquipment[gym][id]=value);save();renderEquipmentProfile();if(gym===sessionGym)renderTracker()}
let restInterval=null,restRemaining=0;
function restSeconds(name){return /胸推|卧推|下拉|划船|腿举|深蹲|分腿蹲|肩推|推举|硬拉|引体/.test(name)?90:60}
function updateRest(){restRemaining=Math.max(0,restRemaining);$('restClock').textContent=`${pad(Math.floor(restRemaining/60))}:${pad(restRemaining%60)}`;if(!restRemaining){clearInterval(restInterval);restInterval=null;$('restClock').textContent='完成';if(navigator.vibrate)navigator.vibrate([150,80,150]);try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);g.gain.value=.08;o.frequency.value=880;o.start();o.stop(a.currentTime+.18)}catch{}setTimeout(stopRest,1800)}}
function startRest(seconds,name){clearInterval(restInterval);restRemaining=seconds;$('restExercise').textContent=`刚完成：${name}`;$('restTimer').classList.add('show');updateRest();restInterval=setInterval(()=>{restRemaining--;updateRest()},1000)}
function stopRest(){clearInterval(restInterval);restInterval=null;$('restTimer').classList.remove('show')}
function workoutVolume(sets){return Math.round(sets.reduce((sum,s)=>sum+doneEntries(s).reduce((a,x)=>a+x.kg*x.reps,0),0))}
function historicalBest(name){return Math.max(0,...data.records.flatMap(r=>r.sets||[]).filter(x=>x.name===name).flatMap(doneEntries).map(x=>x.kg))}
function exerciseHistory(name){return data.records.map(r=>{const ex=r.sets?.find(x=>x.name===name),done=doneEntries(ex);return done.length?{date:r.date,best:Math.max(...done.map(x=>x.kg)),volume:Math.round(done.reduce((a,x)=>a+x.kg*x.reps,0))}:null}).filter(Boolean)}
function lineChart(points,metric){if(!points.length)return '<div class="chart-empty">完成并保存两次训练后，这里会出现趋势图</div>';const shown=points.slice(-8),w=720,h=250,p=46,max=Math.max(1,...shown.map(x=>x[metric])),coords=shown.map((x,i)=>({x:shown.length===1?w/2:p+i*(w-p*2)/(shown.length-1),y:h-p-x[metric]/max*(h-p*2),...x})),line=coords.map((x,i)=>`${i?'L':'M'}${x.x},${x.y}`).join(' '),area=`M${coords[0].x},${h-p} ${line.replace(/^M/,'L')} L${coords.at(-1).x},${h-p} Z`,grid=[0,.5,1].map(n=>`<line class="chart-grid" x1="${p}" y1="${h-p-n*(h-p*2)}" x2="${w-p}" y2="${h-p-n*(h-p*2)}"/><text class="chart-label" x="8" y="${h-p-n*(h-p*2)+4}">${Math.round(max*n)}</text>`).join('');return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="训练趋势图">${grid}<path class="chart-area" d="${area}"/><path class="chart-line" d="${line}"/>${coords.map(x=>`<circle class="chart-dot" cx="${x.x}" cy="${x.y}" r="6"/><text class="chart-value" text-anchor="middle" x="${x.x}" y="${Math.max(16,x.y-12)}">${x[metric]}</text><text class="chart-label" text-anchor="middle" x="${x.x}" y="${h-17}">${esc(x.date.slice(5))}</text>`).join('')}</svg>`}
function renderProgress(){const names=[...new Set(data.records.flatMap(r=>(r.sets||[]).filter(x=>doneEntries(x).length).map(x=>x.name)))],select=$('progressExercise'),current=names.includes(select.value)?select.value:names.at(-1);select.innerHTML=names.length?names.map(x=>`<option ${x===current?'selected':''}>${esc(x)}</option>`).join(''):'<option>暂无训练数据</option>';if(!names.length){$('progressBest').textContent=0;$('progressLast').textContent=0;$('progressSessions').textContent=0;$('progressChart').innerHTML=lineChart([],'best');$('progressHint').textContent='先在训练计划里记录重量和次数。';return}const name=select.value,points=exerciseHistory(name),metric=$('progressMetric').value,last=points.at(-1),best=Math.max(...points.map(x=>x.best));$('progressBest').textContent=best;$('progressLast').textContent=last.best;$('progressSessions').textContent=points.length;$('progressChart').innerHTML=lineChart(points,metric);if(points.length<2)$('progressHint').textContent='再保存一次同动作训练，就能开始比较进步。';else{const first=points[0].best,diff=last.best-first;$('progressHint').textContent=diff>0?`相比第一次记录，最佳重量提高了 ${diff}kg。`:diff<0?'近期重量低于首次记录，优先保证动作质量与恢复。':'重量保持稳定；可以继续提高次数或动作质量。'}}
function render(){const n=new Date(),t=dateKey(n),ok=data.checkins.includes(t);$('today').textContent=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(n);$('checkinBtn').disabled=ok;$('checkinBtn').textContent=ok?'今日已完成 ✓':'完成今日打卡';$('statusTag').textContent=ok?'今日已打卡':'今日待完成';$('monthCount').textContent=data.checkins.filter(x=>x.startsWith(t.slice(0,7))).length;$('totalCount').textContent=data.checkins.length;const m=new Date(n);m.setDate(n.getDate()-((n.getDay()+6)%7));m.setHours(0,0,0,0);$('weekCount').textContent=data.checkins.filter(x=>new Date(x+'T00:00:00')>=m).length;let s=0,c=new Date(n);if(!ok)c.setDate(c.getDate()-1);while(data.checkins.includes(dateKey(c))){s++;c.setDate(c.getDate()-1)}$('streak').textContent=s;renderTracker();renderEquipmentProfile();records();calendar(n);renderBody();renderWearable();renderRewards();renderProgress();$('gym').value=autoGym()}
function records(){const b=$('records');if(!data.records.length){b.innerHTML='<p class="empty">还没有记录，练完第一套后保存吧</p>';return}b.innerHTML=[...data.records].reverse().slice(0,12).map(r=>{const d=new Date(r.date+'T00:00:00'),warmupDone=r.warmup?.filter(x=>x.done).length||0,extra=`${r.warmup?.length?`　热身${warmupDone}/${r.warmup.length}`:''}${r.volume?`　总容量${r.volume}kg`:''}${r.prs?.length?`　🏆 ${r.prs.length}项新纪录`:''}`;return `<article class="record"><div class="record-date"><strong>${d.getDate()}</strong><small>${d.getMonth()+1}月</small></div><div class="record-body"><b>${esc(r.type)} · ${esc(r.duration)}分钟</b><p>${esc(r.gym||'')}${r.feeling?'　'+esc(r.feeling):''}${extra}${r.note?'　'+esc(r.note):''}</p></div></article>`}).join('')}
function calendar(n){$('calendarTitle').textContent=`${n.getFullYear()} 年 ${n.getMonth()+1} 月`;const f=new Date(n.getFullYear(),n.getMonth(),1),ds=new Date(n.getFullYear(),n.getMonth()+1,0).getDate();let h='<span class="day blank"></span>'.repeat((f.getDay()+6)%7);for(let i=1;i<=ds;i++){const d=new Date(n.getFullYear(),n.getMonth(),i),k=dateKey(d);h+=`<span class="day ${data.checkins.includes(k)?'checked':''} ${k===dateKey(n)?'today':''}">${i}</span>`}$('calendar').innerHTML=h}function toast(x){$('toast').textContent=x;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function addRecord(r){const i=data.records.findIndex(x=>x.date===r.date&&x.type===r.type);if(i>=0)data.records[i]=r;else data.records.push(r);if(!data.checkins.includes(r.date))data.checkins.push(r.date);save();render()}
$('planChoice').onchange=e=>{const previous=selectedPlan;if(document.querySelector('.set-check:checked,.warmup-check:checked')&&!confirm('切换计划会清空当前尚未保存的组数和热身勾选，确定切换吗？')){e.target.value=String(selectedPlan);return}warmupState[previous]=[];selectedPlan=+e.target.value;renderTracker()};
$('sessionGymChoice').onchange=e=>{if(document.querySelector('.set-check:checked')&&!confirm('切换地点会按新器械档案重新生成动作，确定切换吗？')){e.target.value=sessionGym;return}sessionGym=e.target.value;renderTracker()};
$('equipmentGym').onchange=renderEquipmentProfile;$('equipmentAll').onclick=()=>setAllEquipment(true);$('equipmentNone').onclick=()=>{if(confirm('将这家店的器械全部取消，然后按现场重新勾选？'))setAllEquipment(false)};
$('restMinus').onclick=()=>{restRemaining-=15;updateRest()};$('restPlus').onclick=()=>{restRemaining+=15;updateRest()};$('restSkip').onclick=stopRest;
$('progressExercise').onchange=renderProgress;$('progressMetric').onchange=renderProgress;
$('finishWorkout').onclick=()=>{const p=plans[selectedPlan],warmup=[...document.querySelectorAll('.warmup-step')].map(e=>({name:e.dataset.name,done:e.querySelector('.warmup-check').checked})),sets=[...document.querySelectorAll('.exercise-track')].map(e=>({name:e.dataset.name,skipped:e.classList.contains('skipped'),entries:[...e.querySelectorAll('.set-box')].map(x=>({done:x.querySelector('.set-check').checked,kg:x.querySelector('.kg').value,reps:x.querySelector('.reps').value}))}));if(!sets.some(x=>!x.skipped&&x.entries.some(y=>y.done)))return toast('请至少勾选一组实际完成的训练');const prs=sets.filter(x=>Math.max(0,...doneEntries(x).map(y=>y.kg))>historicalBest(x.name)).map(x=>x.name),volume=workoutVolume(sets);if(sessionGym.includes('铁锤')&&data.hammerUsed<7)data.hammerUsed++;stopRest();addRecord({date:dateKey(),gym:sessionGym,type:p.type,duration:'75',feeling:'按现场状态调整完成',note:p.cardio,warmup,sets,volume,prs});warmupState={};selectedPlan=nextIndex();sessionGym=autoGym();save();render();toast(prs.length?`训练已保存，出现 ${prs.length} 项新纪录！`:`训练已保存｜总容量 ${volume}kg`)};
$('checkinBtn').onclick=()=>{const k=dateKey();if(!data.checkins.includes(k))data.checkins.push(k);save();render();toast('打卡成功！')};$('workoutForm').onsubmit=e=>{e.preventDefault();addRecord({date:dateKey(),gym:$('gym').value,type:$('type').value,duration:$('duration').value,feeling:$('feeling').value,note:$('note').value.trim()});$('saveHint').textContent='已保存并打卡'};$('clearBtn').onclick=()=>{if(confirm('确定清空全部记录吗？器械档案也会恢复默认。')){data={checkins:[],records:[],body:[],wearable:[],redeemed:[],hammerUsed:0};ensureData();selectedPlan=0;sessionGym=autoGym();save();render()}};
$('bodyForm').onsubmit=e=>{e.preventDefault();const x={date:dateKey(),weight:$('bodyWeight').value,waist:$('waist').value,chest:$('chest').value,arm:$('arm').value},i=data.body.findIndex(y=>y.date===x.date);if(i>=0)data.body[i]=x;else data.body.push(x);save();render();toast('身体数据已保存，积分已更新')};function renderBody(){$('bodyHistory').innerHTML=[...data.body].reverse().slice(0,5).map(x=>`${esc(x.date)}　${esc(x.weight)}kg　腰${esc(x.waist||'-')}　胸${esc(x.chest||'-')}　臂${esc(x.arm||'-')}cm`).join('<br>')||'暂无身体数据'}
$('wearableForm').onsubmit=e=>{e.preventDefault();const x={date:dateKey(),strength:+$('strengthKcal').value||0,cardio:+$('cardioKcal').value||0,avgHr:+$('avgHr').value||0,maxHr:+$('maxHr').value||0,abs:$('absDone').checked},i=data.wearable.findIndex(y=>y.date===x.date);if(i>=0)data.wearable[i]=x;else data.wearable.push(x);save();render();toast('手环数据已保存，积分已更新')};function kcal(x){return(+x.strength||0)+(+x.cardio||0)}function renderWearable(){const now=new Date(),t=dateKey(now),monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));monday.setHours(0,0,0,0);const today=data.wearable.find(x=>x.date===t);$('todayKcal').textContent=today?kcal(today):0;$('weekKcal').textContent=data.wearable.filter(x=>new Date(x.date+'T00:00:00')>=monday).reduce((a,x)=>a+kcal(x),0);$('monthKcal').textContent=data.wearable.filter(x=>x.date.startsWith(t.slice(0,7))).reduce((a,x)=>a+kcal(x),0);if(today){$('strengthKcal').value=today.strength||'';$('cardioKcal').value=today.cardio||'';$('avgHr').value=today.avgHr||'';$('maxHr').value=today.maxHr||'';$('absDone').checked=!!today.abs}}
function weekKey(s){const d=new Date(s+'T00:00:00');d.setDate(d.getDate()-((d.getDay()+6)%7));return dateKey(d)}function rewardData(){const mains=new Set(data.records.filter(r=>planIndexForType(r.type)>=0||['恢复训练','自由训练'].includes(r.type)).map(r=>r.date)),cardio=new Set(data.wearable.filter(x=>(+x.cardio||0)>0).map(x=>x.date)),abs=new Set(data.wearable.filter(x=>x.abs).map(x=>x.date)),weeks=new Set(data.body.map(x=>weekKey(x.date)));let streakBonus=0;[...new Set(data.checkins)].sort().forEach((d,i,a)=>{if(i&&((new Date(d)-new Date(a[i-1]))/86400000===1))streakBonus+=5});return{main:mains.size,cardio:cardio.size,abs:abs.size,weeks:weeks.size,points:mains.size*20+cardio.size*10+abs.size*5+weeks.size*10+streakBonus}}function renderRewards(){const r=rewardData(),levels=[[0,'青铜起步'],[100,'白银坚持'],[250,'黄金塑形'],[500,'铂金自律'],[800,'钻石体魄']],idx=Math.max(0,levels.findLastIndex(x=>r.points>=x[0])),cur=levels[idx],next=levels[idx+1];$('points').textContent=r.points;$('levelName').textContent=cur[1];$('nextReward').textContent=next?`距${next[1]}还差 ${next[0]-r.points} 分`:'已达到最高等级';$('rewardProgress').style.width=next?`${Math.min(100,(r.points-cur[0])/(next[0]-cur[0])*100)}%`:'100%';const gifts=[[50,'选一首新训练歌 / 一杯无糖饮品'],[100,'奖励一件小型健身用品，预算≤30元'],[250,'奖励一次电影或休闲活动，预算≤60元'],[500,'奖励一件训练服，预算≤120元'],[800,'安排一次体测或升级实用装备']];$('rewards').innerHTML='<b>可兑现奖励：</b><br>'+gifts.map(x=>`${r.points>=x[0]?'✅':'🔒'} ${x[0]}分：${x[1]}`).join('<br>')}
$('exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`fitness-backup-${dateKey()}.json`;a.click();URL.revokeObjectURL(a.href)};$('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.records))throw 0;data=x;ensureData();sessionGym=autoGym();save();render();toast('备份导入成功')}catch{alert('备份文件无效')}};r.readAsText(f)};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
